return {
	"RRethy/base16-nvim",
	require("base16-colorscheme").setup({
		base00 = string.format("#%s", nixCats("stylix.base00")),
		base01 = string.format("#%s", nixCats("stylix.base01")),
		base02 = string.format("#%s", nixCats("stylix.base02")),
		base03 = string.format("#%s", nixCats("stylix.base03")),
		base04 = string.format("#%s", nixCats("stylix.base04")),
		base05 = string.format("#%s", nixCats("stylix.base05")),
		base06 = string.format("#%s", nixCats("stylix.base06")),
		base07 = string.format("#%s", nixCats("stylix.base07")),
		base08 = string.format("#%s", nixCats("stylix.base08")),
		base09 = string.format("#%s", nixCats("stylix.base09")),
		base0A = string.format("#%s", nixCats("stylix.base0A")),
		base0B = string.format("#%s", nixCats("stylix.base0B")),
		base0C = string.format("#%s", nixCats("stylix.base0C")),
		base0D = string.format("#%s", nixCats("stylix.base0D")),
		base0E = string.format("#%s", nixCats("stylix.base0E")),
		base0F = string.format("#%s", nixCats("stylix.base0F")),
	}),
}
