return {

	{
		"xiyaowong/transparent.nvim",
		require("transparent").setup({
			groups = {
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
				"Operator",
				"Structure",
				"LineNr",
				"LineNrAbove",
				"LineNrBelow",
				"NonText",
				"SignColumn",
				"CursorLine",
				"CursorLineNr",
				"CursorLineSign",
				"StatusLine",
				"StatusLineNC",
				"EndOfBuffer",
			},
			extra_groups = {
				"DiagnosticSignWarn",
				"DiagnosticSignError",
				"DiagnosticSignOk",
				"DiagnosticSignInfo",
				"DiagnosticSignHint",
				"GitSignsAdd",
				"GitSignsDelete",
				"GitSignsChange",
				"RenderMarkdownH1Bg",
				"RenderMarkdownH2Bg",
				"RenderMarkdownH3Bg",
				"RenderMarkdownH4Bg",
				"RenderMarkdownH5Bg",
				"RenderMarkdownH6Bg",
			},
			exclude_groups = {},
		}),
	},
}
